services:
  sqlserver:
    image: d
    container_name: ClinicAPI-SQL
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: ClinicAPI-Redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  sqlserver_data:
